[package]
name = "transact"
version = "0.1.7"
authors = ["Bitwise IO, Inc.", "Cargill Incorporated"]
edition = "2018"
license = "Apache-2.0"
readme = "../README.md"
description = """\
    Transact is a transaction execution platform designed to be used as \
    a library or component when implementing distributed ledgers, including \
    blockchains.
"""
repository = "http://github.com/hyperledger/transact"

[package.metadata.docs.rs]
features = ["sawtooth-compat", "redis-db"]

[dependencies]
hex = "0.3"
protobuf = "2"
rand = "0.6"
sha2 = "0.8"
lmdb-zero = ">=0.4.1"
log = { version = "0.4", features = ["std"] }
cbor-codec = "0.7"
libc = ">=0.2.35"
openssl = "0.10"
uuid = { version = "0.7", features = ["v4"] }
sawtooth-sdk = { version = "0.3", optional = true }
ursa = { version = "0.2.0", optional = true }
redis = { version = "0.13.0", default-features = false, optional = true }

[dev-dependencies]
rand_hc = "0.1"
sawtooth-xo = "0.3"

[build-dependencies]
protoc-rust = "2"

[features]
default = []
nightly = []
experimental = [
    "contract",
    "contract-address",
    "redis-db",
]
sawtooth-compat = ["sawtooth-sdk"]
ursa-compat = ["ursa"]
redis-db = ["redis"]
contract = []
contract-address = ["contract"]
contract-address-key-hash = ["contract-address"]
